server:
  port: 8086
spring:
  application:
    name: comsumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.81.250.30:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
