server:
  port: 8090
spring:
  application:
    name: consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.81.250.30:3306/qa?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: k12
  cloud:
    nacos:
      discovery:
        server-addr: 172.81.250.30:8848
        group: CLOUDALI
    sentinel:
      transport:
        dashboard: 172.81.250.30:9817
        port: 8719
        clientIp: 101.67.148.78
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.study.nacos.producer.entity
  configuration:
    map-underscore-to-camel-case: true
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
